---
{{- if or .Values.secrets (include "kestra.k8s-config" $) }}
{{ $merged := (merge (dict "Component" "secret") $) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kestra.fullname" $merged }}
  labels:
    {{- include "kestra.labels" $merged | nindent 4 }}
type: Opaque
data:
{{- if .Values.secrets }}
  application-secrets.yml: {{.Values.secrets | toYaml | b64enc | quote }}
{{- end }}
{{- if include "kestra.k8s-config" $ }}
  application-k8s.yml: {{ include "kestra.k8s-config" $ | b64enc | quote }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sftp-creds
type: Opaque
data:
  # base64 encoded twice
  SECRET_AML_SFTP: {{ .Values.customsecrets.amlsftp }}
  SECRET_GGR_SFTP: {{.Values.customsecrets.ggrsftp  }}
  SECRET_MI_SFTP: {{ .Values.customsecrets.misftp }}
  SECRET_AGCO-SFTP: {{ .Values.customsecrets.agcosftp }}
---