apiVersion: v2
name: custom-kestra-ontario
description: Infinitely scalable, event-driven, language-agnostic orchestration and scheduling platform to manage millions of workflows declaratively in code.
version: 0.4.0
appVersion: "0.4.0"
dependencies:
- name: elasticsearch
  version: ^8.5.1
  repository: https://helm.elastic.co
  condition: elasticsearch.enabled
- name: kafka
  version: ^29.0.3
  repository: https://charts.bitnami.com/bitnami
  condition: kafka.enabled
- name: minio
  version: ^14.7.9
  repository: https://charts.bitnami.com/bitnami
  condition: minio.enabled
- name: postgresql
  condition: postgresql.enabled
  repository: https://charts.bitnami.com/bitnami
  version: ^15.5.31
